SET NOCOUNT ON; select LTRIM(RTRIM(PARTY_ID)) as PARTY_ID,(select DEALER_NUMBER from C_B_DEALER where DEALER_ID=C_B_DEALER.ROWID_OBJECT) DEALER_NO,RELATION_START_DATE,RELATION_END_DATE from C_REL_PARTY_DEALER
where exists(select 1 from C_B_PARTY where TYPE='P' and C_B_PARTY.HUB_STATE_IND=1
and exists(select 1 from C_B_PARTY_STATUS where STATUS_CODE=1 and C_B_PARTY_STATUS.HUB_STATE_IND=1
and STATUS_TYPE in('A','L')))
and HUB_STATE_IND=1 and STATUS_CODE=1
and RELATION_END_DATE is null