USE MDM_CM;
update top(250) C_S_DF_CAR_REL_CLOSE_LOAD set load_flg=1 where load_flg=0 and role_code='B';

delete from mdm_cm..C_S_DF_CAR_REL_CLOSE;

insert into C_S_DF_CAR_REL_CLOSE(PKEY_SRC_OBJECT,ROWID_OBJECT,
VERSION_SEQ,LAST_UPDATE_DATE,UPDATED_BY,SRC_ROWID,RELATION_END_DATE,STATUS_CODE)
select 
pkey,ROWID_OBJECT,
VERSION_SEQ,LAST_UPDATE_DATE,UPDATED_BY,SRC_ROWID,RELATION_END_DATE,STATUS_CODE
from 
C_S_DF_CAR_REL_CLOSE_LOAD where load_flg=1;

update C_S_DF_CAR_REL_CLOSE_LOAD set load_flg=2 where load_flg=1;
