 USE MDM_CM;
truncate table C_S_DECEASED_FLG_PERSON;
insert top (500) into   C_S_DECEASED_FLG_PERSON (PKEY_SRC_OBJECT,ROWID_OBJECT,VERSION_SEQ,LAST_UPDATE_DATE,HUB_STATE_IND,SRC_ROWID,DECEASED_FLAG,DECEASED_date)
  select CONCAT(rtrim(ROWID_OBJECT),'|MDM|Update') as PKEY_SRC_OBJECT,ROWID_OBJECT,1 as VERSION_SEQ,GETDATE() as LAST_UPDATE_DATE,1 as HUB_STATE_IND ,'MDM' as SRC_ROWID,0 as DECEASED_FLAG,NULL
  from C_B_PERSON where DECEASED_FLAG is  null and HUB_STATE_IND=1 and PARTY_ID in (select ROWID_OBJECT from C_B_PARTY where HUB_STATE_IND='1' and TYPE='P' and COUNTRY_CODE='NO');