update top(700) MDM_CUSTOM..TMP_C_S_MDM_PHONE_DA  set load_flg=1 where load_flg=0;

delete from mdm_cm..[C_S_MDM_PHONE_DA];

INSERT INTO mdm_cm..[C_S_MDM_PHONE_DA]
           (PKEY_SRC_OBJECT,ROWID_OBJECT,VERSION_SEQ,LAST_UPDATE_DATE,
UPDATED_BY,SRC_ROWID,RELATION_START_DATE)
select 
PKEY_SRC_OBJECT,ROWID_OBJECT,VERSION_SEQ,LAST_UPDATE_DATE,
UPDATED_BY,SRC_ROWID,RELATION_START_DATE
from 
MDM_CUSTOM..TMP_C_S_MDM_PHONE_DA where load_flg=1;

update MDM_CUSTOM..TMP_C_S_MDM_PHONE_DA set load_flg=2 where load_flg=1;
