 TRUNCATE TABLE C_S_LEGAL_NAME_UPDATE;

 INSERT INTO C_S_LEGAL_NAME_UPDATE(PKEY_SRC_OBJECT,ROWID_OBJECT,VERSION_SEQ,LAST_UPDATE_DATE,UPDATED_BY,SRC_ROWID,LEGAL_NAME)
 SELECT CONCAT('MDM|',RTRIM(C_B_ORGANIZATION.ROWID_OBJECT),'|LG'),C_B_ORGANIZATION.ROWID_OBJECT,'1',GETDATE(),'admin','MDM',NAVN
 FROM C_B_ORGANIZATION,MDM_CM..C_B_BRREG_ORGANIZATIONS
 WHERE ORGANISASJONSNUMMER=ORGANIZATION_NUMBER
 AND NAVN<>LEGAL_NAME --AND ALIAS_NAME=NAVN
 AND LEGAL_NAME IS NOT NULL AND ORG_NO IS NULL
 AND EXISTS(SELECT 1 FROM C_B_PARTY WHERE C_B_PARTY.ROWID_OBJECT=PARTY_ID
 AND BRREG_CLEANSED=1)
 and not exists (select 1 from C_B_ORGANIZATION_HIST B where B.PARTY_ID=C_B_ORGANIZATION.PARTY_ID
 and B.UPDATED_BY in ('kenneths','CAPI-KENNETH.SKARSTAD@MOLLER.NO'));

 INSERT INTO C_S_LEGAL_NAME_UPDATE(PKEY_SRC_OBJECT,ROWID_OBJECT,VERSION_SEQ,LAST_UPDATE_DATE,UPDATED_BY,SRC_ROWID,LEGAL_NAME)
 SELECT CONCAT('MDM|',RTRIM(C_B_ORGANIZATION.ROWID_OBJECT),'|LG'),C_B_ORGANIZATION.ROWID_OBJECT,'1',GETDATE(),'admin','MDM',NAVN
 FROM C_B_ORGANIZATION,MDM_CM..C_B_BRREG_ORGANIZATIONS
 WHERE ORGANISASJONSNUMMER=ORG_NO 
 AND NAVN<>LEGAL_NAME
 --AND ALIAS_NAME=NAVN
 AND LEGAL_NAME IS NOT NULL AND ORGANIZATION_NUMBER IS NULL
 AND EXISTS(SELECT 1 FROM C_B_PARTY WHERE C_B_PARTY.ROWID_OBJECT=PARTY_ID
 AND BRREG_CLEANSED=1)
  and not exists (select 1 from C_B_ORGANIZATION_HIST B where B.PARTY_ID=C_B_ORGANIZATION.PARTY_ID
 and B.UPDATED_BY in ('kenneths','CAPI-KENNETH.SKARSTAD@MOLLER.NO'));
