
-- 1. ADDRESS
TRUNCATE TABLE MNET_COPY..C_B_ADDRESS ;

INSERT INTO  MNET_COPY..C_B_ADDRESS ([ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[ADDRESS_LINE_1]
      ,[POSTAL_CODE]
      ,[CITY_NAME]
      ,[CO_NAME]
      ,[COUNTRY_ISO2_CODE]
      ,[STD_ADDRESS_LN1]
      ,[STD_CITY]
      ,[STD_POSTAL_CODE]
      ,[STD_COUNTRY]
      ,[ADDRESS_PROCESS_STATUS]
      ,[MAILABILITY_SCORE]
      ,[ADDRESS_VALIDATED])
SELECT [ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
	  ,[ADDRESS_LINE_1]
      ,[POSTAL_CODE]
      ,CITY AS [CITY_NAME]
      ,CARE_OF AS [CO_NAME]
      ,[COUNTRY_ISO2_CODE]
	  , NULL AS [STD_ADDRESS_LN1]
	  , NULL AS [STD_CITY]
	  , NULL AS [STD_POSTAL_CODE]
	  , NULL AS [STD_COUNTRY]
	  , NULL AS [ADDRESS_PROCESS_STATUS]
	  , NULL AS [MAILABILITY_SCORE]
	  , NULL AS [ADDRESS_VALIDATED]
	   FROM MDM_CM..C_B_ADDRESS A
	   WHERE EXISTS (SELECT 1 
	                 FROM MDM_CM..C_REL_PARTY_ADDRESS B 
					 WHERE A.[ROWID_OBJECT]=B.ADDRESS_ID 
					 AND B.ADDRESS_TYPE='ST' 
					 AND B.NON_LEGAL_SUBORG_ID IS NULL 
					 AND B.HUB_STATE_IND='1' )
	   AND HUB_STATE_IND='1';
	   
-- 2. CAR	   
TRUNCATE TABLE MNET_COPY..C_B_CAR ;

INSERT INTO MNET_COPY..C_B_CAR([ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[REGISTRATION_NUMBER]
      ,[VEHICLE_IDENTIFICATION_NO]
      ,[CAR_MODEL]
      ,[MODEL_YEAR]
      ,[BRAND_CODE]
      ,[NEXT_PMVI]
      ,[LATEST_PMVI]
      ,[LAST_REG_DATE]
      ,[FIRST_REG_DATE]
      ,[VEHICLE_GROUP])
SELECT [ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[REGISTRATION_NUMBER]
      ,[VEHICLE_IDENTIFICATION_NO]
      ,[CAR_MODEL]
      ,[MODEL_YEAR]
      ,[BRAND_CODE]
      ,[NEXT_PMVI]
      ,[LATEST_PMVI]
      ,[LAST_REG_DATE]
      ,[FIRST_REG_DATE]
      ,[VEHICLE_GROUP]
	   FROM MDM_CM..C_B_CAR 
	   WHERE HUB_STATE_IND='1';
	   

-- 3. PARTY	   
TRUNCATE TABLE 	MNET_COPY..C_B_PARTY ; 

INSERT INTO  MNET_COPY..C_B_PARTY(
[ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[FIRST_NAME]
      ,[LAST_NAME]
      ,[ORGANIZATION_NUMBER]
      ,[ORGANIZATION_NAME]
      ,[BIRTHDATE]
      ,[GENDER_CODE]
      ,[PARTY_TYPE_CODE]
      ,[KRID]
      ,[NLRID]
      ,[SAP_ID]
      ,[PARTY_NAME]
      ,[OFFICIAL_NAME]
      ,[OFFICIAL_ORG_NO]
      ,[ALIAS_NAME]
      ,[BRREG_CLEANSED]
)
SELECT * FROM 
(   
SELECT A.[ROWID_OBJECT]
      ,A.[CREATOR]
      ,A.[CREATE_DATE]
      ,A.[UPDATED_BY]
      ,A.[LAST_UPDATE_DATE]
      ,A.[CONSOLIDATION_IND]
      ,A.[DELETED_IND]
      ,A.[DELETED_BY]
      ,A.[DELETED_DATE]
      ,A.[LAST_ROWID_SYSTEM]
      ,A.[DIRTY_IND]
      ,A.[INTERACTION_ID]
      ,A.[HUB_STATE_IND]
      ,A.[CM_DIRTY_IND]
	  ,B.FIRST_NAME
	  ,B.SURNAME AS LAST_NAME
	  ,NULL AS [ORGANIZATION_NUMBER]
	  ,NULL AS [ORGANIZATION_NAME]
	  ,C.BIRTHDATE AS [BIRTHDATE]
	  ,NULL AS [GENDER_CODE]
	  ,A.TYPE AS [PARTY_TYPE_CODE]
	  ,NULL AS [KRID]
	  ,NULL AS [NLRID]
	  ,NULL AS [SAP_ID]
	  ,NULL AS [PARTY_NAME]
	  ,NULL AS [OFFICIAL_NAME]
	  ,NULL AS [OFFICIAL_ORG_NO]
	  ,NULL AS [ALIAS_NAME]
	  ,NULL AS [BRREG_CLEANSED]
FROM MDM_CM..C_B_PARTY A INNER JOIN MDM_CM..C_B_PERSON B 
ON (A.ROWID_OBJECT=B.PARTY_ID AND A.TYPE='P')
LEFT JOIN MDM_CM..C_B_BIRTHDATE C ON A.ROWID_OBJECT=C.PARTY_ID AND C.HUB_STATE_IND='1'
WHERE A.HUB_STATE_IND='1'
AND A.TYPE='P'
UNION
SELECT A.[ROWID_OBJECT]
      ,A.[CREATOR]
      ,A.[CREATE_DATE]
      ,A.[UPDATED_BY]
      ,A.[LAST_UPDATE_DATE]
      ,A.[CONSOLIDATION_IND]
      ,A.[DELETED_IND]
      ,A.[DELETED_BY]
      ,A.[DELETED_DATE]
      ,A.[LAST_ROWID_SYSTEM]
      ,A.[DIRTY_IND]
      ,A.[INTERACTION_ID]
      ,A.[HUB_STATE_IND]
      ,A.[CM_DIRTY_IND]
	  ,NULL AS FIRST_NAME
	  ,NULL AS LAST_NAME
	  ,B.ORGANIZATION_NUMBER
	  ,B.ALIAS_NAME AS [ORGANIZATION_NAME]
	  ,NULL AS [BIRTHDATE]
	  ,NULL AS [GENDER_CODE]
	  ,A.TYPE AS [PARTY_TYPE_CODE]
	  ,NULL AS [KRID]
	  ,NULL AS [NLRID]
	  ,NULL AS [SAP_ID]
	  ,NULL AS [PARTY_NAME]
	  ,NULL AS [OFFICIAL_NAME]
	  ,NULL AS [OFFICIAL_ORG_NO]
	  ,NULL AS [ALIAS_NAME]
	  ,NULL AS [BRREG_CLEANSED]
FROM MDM_CM..C_B_PARTY A INNER JOIN MDM_CM..C_B_ORGANIZATION B 
ON (A.ROWID_OBJECT=B.PARTY_ID AND A.TYPE='O')
WHERE A.HUB_STATE_IND='1'
AND A.TYPE='O'
) PARTY;


-- 4. ELECTRONIC ADDRESS RELATION
TRUNCATE TABLE MNET_COPY..C_B_PARTY_EL_ADDRESS ;

INSERT INTO MNET_COPY..C_B_PARTY_EL_ADDRESS([ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[ELECTRONIC_ADDRESS]
      ,[ELECTRONIC_ADDRESS_TYPE]
      ,[PARTY_ID]
      ,[OPT_IN_IND]
      ,[RELATION_START_DATE]
      ,[RELATION_END_DATE]
	  )
SELECT [ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[ELECTRONIC_ADDRESS]
      ,CASE WHEN TYPE = 'S' THEN 'E' ELSE '' END  AS [ELECTRONIC_ADDRESS_TYPE]
      ,[PARTY_ID]
      ,NULL AS [OPT_IN_IND]
      ,[RELATION_START_DATE]
      ,[RELATION_END_DATE]
	   FROM  MDM_CM..C_B_ELECTRONIC_ADDRESS A
	   WHERE HUB_STATE_IND='1'
	   and NON_LEGAL_SUBORG_ID IS NULL
	   and  EXISTS (SELECT 1 FROM  MDM_CM..C_B_PARTY B WHERE B.ROWID_OBJECT=A.PARTY_ID AND B.HUB_STATE_IND='1') ;
	   
	   
-- 5. PARTY SRC COUNTRY	   
TRUNCATE TABLE MNET_COPY..C_B_PARTY_SRC_COUNTRY ;

INSERT INTO MNET_COPY..C_B_PARTY_SRC_COUNTRY([ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[PARTY_ID]
      ,[COUNTRY_ISO2_CODE])   
SELECT [ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,ROWID_OBJECT AS [PARTY_ID]
      ,COUNTRY_CODE AS [COUNTRY_ISO2_CODE]
      FROM MDM_CM..C_B_PARTY
	  WHERE HUB_STATE_IND='1';
	  
	  
-- 6. CUSTOMER ROLE	  
TRUNCATE TABLE MNET_COPY..C_LU_CUSTOMER_ROLE ;	  

INSERT INTO MNET_COPY..C_LU_CUSTOMER_ROLE(
[ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[ROLE_CODE]
      ,[ROLE_DISPLAY])
SELECT [ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,CODE AS [ROLE_CODE]
      ,DESCRIPTION AS [ROLE_DISPLAY]
	   FROM MDM_CM..C_LU_CUSTOMER_ROLE	;

	   
-- 7. BRAND CODE


TRUNCATE TABLE MNET_COPY..[C_LU_BRAND] ;	

INSERT INTO MNET_COPY..[C_LU_BRAND] ([ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[BRAND_CODE]
      ,[BRAND_NAME])
SELECT [ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,CODE AS [BRAND_CODE]
      ,DESCRIPTION AS [BRAND_NAME]
	   FROM MDM_CM..C_LU_BRAND ;
	   

	   

	   
	   
	   
--9. Consent


TRUNCATE TABLE MNET_Copy..C_REL_PARTY_CSENT_PLCY ;

INSERT INTO MNET_Copy..C_REL_PARTY_CSENT_PLCY ([ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[PARTY_ID]
      ,[BRAND_CODE]
      ,[POLICY_ID]
      ,[PURPOSE_TYPE]
      ,[POST_CONSENT_FLG]
      ,[PHONE_CONSENT_FLG]
      ,[SMS_CONSENT_FLG]
      ,[EMAIL_CONSENT_FLG]
      ,[RETENTION_END_DATE]
      ,[ACTIVE_CONSENT_FLG]
      ,[COMMENT]
      ,[OTHER_ELTRNC_METHODS_FLG])
SELECT B.[ROWID_OBJECT]
      ,B.[CREATOR]
      ,B.[CREATE_DATE]
      ,B.[UPDATED_BY]
      ,B.[LAST_UPDATE_DATE]
      ,B.[CONSOLIDATION_IND]
      ,B.[DELETED_IND]
      ,B.[DELETED_BY]
      ,B.[DELETED_DATE]
      ,B.[LAST_ROWID_SYSTEM]
      ,B.[DIRTY_IND]
      ,B.[INTERACTION_ID]
      ,B.[HUB_STATE_IND]
      ,B.[CM_DIRTY_IND]
	  ,A.PARTY_ID
	  ,B.BRAND_ID AS [BRAND_CODE]
	  ,'1' AS [POLICY_ID]
	  ,'M' AS [PURPOSE_TYPE]
	  ,C.OTHERS AS [POST_CONSENT_FLG]
	  ,C.OTHERS AS [PHONE_CONSENT_FLG]
	  ,C.SMS AS [SMS_CONSENT_FLG]
	  ,C.EMAIL AS [EMAIL_CONSENT_FLG]
	  ,NULL AS [RETENTION_END_DATE]
	  ,B.ACTIVE_CONSENT_FLAG
	  ,NULL AS [COMMENT]
	  ,C.OTHERS AS [OTHER_ELTRNC_METHODS_FLG]
FROM MDM_CM..C_B_PERSON A INNER JOIN MDM_CM..C_B_CONSENT B ON A.ROWID_OBJECT=B.PERSON_ID
LEFT JOIN  (SELECT COMM_PREF.* FROM 
(SELECT PARTY_ID,BRAND_ID,E AS EMAIL,S AS SMS,O AS OTHERS
FROM
(
  SELECT PARTY_ID,BRAND_ID, COMMUNICATION_CHANNEL_ID,ACTIVE_PREFERENCE_FLAG
  FROM MDM_CM..C_B_COMMUNICATION_PREF  
) D
PIVOT
(
  MAX(ACTIVE_PREFERENCE_FLAG)
  FOR COMMUNICATION_CHANNEL_ID IN (E,S,O)
) PIV) COMM_PREF) C ON A.PARTY_ID=C.PARTY_ID
WHERE  B.BRAND_ID=C.BRAND_ID
AND EXISTS (SELECT 1 FROM  MDM_CM..C_B_PARTY WHERE C_B_PARTY.ROWID_OBJECT=A.party_id AND C_B_PARTY.HUB_STATE_IND='1')
AND A.HUB_STATE_IND='1'
AND B.HUB_STATE_IND='1'
ORDER BY A.PARTY_ID,B.BRAND_ID ;

--10. Address Relation
	   
	   
	   
	   

TRUNCATE TABLE MNET_Copy..C_REL_PARTY_ADDRESS ;	  

INSERT INTO  MNET_Copy..C_REL_PARTY_ADDRESS ([ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[ADDRESS_TYPE]
      ,[PARTY_ID]
      ,[ADDRESS_ID]
      ,[OPT_IN_IND]
      ,[RELATION_START_DATE]
      ,[RELATION_END_DATE])
select [ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,'P' AS [ADDRESS_TYPE]
      ,[PARTY_ID]
      ,[ADDRESS_ID]
      ,NULL as [OPT_IN_IND]
      ,[RELATION_START_DATE]
      ,[RELATION_END_DATE] 
	  from MDM_CM..C_REL_PARTY_ADDRESS A
where HUB_STATE_IND='1'
and ADDRESS_TYPE='ST'
and NON_LEGAL_SUBORG_ID IS NULL 
and EXISTS (SELECT 1 FROM  MDM_CM..C_B_PARTY WHERE C_B_PARTY.ROWID_OBJECT=A.PARTY_ID AND C_B_PARTY.HUB_STATE_IND='1')
and EXISTS (SELECT 1 FROM  MDM_CM..C_B_ADDRESS WHERE C_B_ADDRESS.ROWID_OBJECT=A.ADDRESS_ID AND C_B_ADDRESS.HUB_STATE_IND='1') ;


--11. Car Relation



TRUNCATE TABLE MNET_Copy..C_REL_PARTY_CAR ;	  

INSERT INTO  MNET_Copy..C_REL_PARTY_CAR ([ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,[VEHICLE_IDENTIFICATION_NO]
      ,[RELATION_START_DATE]
      ,[RELATION_END_DATE]
      ,[PARTY_ID]
      ,[ROLE_CODE]
      ,[STATUS_CODE]
      ,[CAR_OWNER_VERIFIED]
      ,[C_REL_START_DATE]
      ,[CAR_ID]
      ,[DELETE_STATUS]
      ,[PARTY_COUNTRY_ISO_CODE]
      ,[CAR_COUNTRY_ISO_CODE] )
select [ROWID_OBJECT]
      ,[CREATOR]
      ,[CREATE_DATE]
      ,[UPDATED_BY]
      ,[LAST_UPDATE_DATE]
      ,[CONSOLIDATION_IND]
      ,[DELETED_IND]
      ,[DELETED_BY]
      ,[DELETED_DATE]
      ,[LAST_ROWID_SYSTEM]
      ,[DIRTY_IND]
      ,[INTERACTION_ID]
      ,[HUB_STATE_IND]
      ,[CM_DIRTY_IND]
      ,NULL as [VEHICLE_IDENTIFICATION_NO]
      ,[RELATION_START_DATE]
      ,[RELATION_END_DATE]
      ,[PARTY_ID]
      ,[ROLE_CODE]
      ,[STATUS_CODE]
      ,NULL as [CAR_OWNER_VERIFIED]
      ,NULL as [C_REL_START_DATE]
      ,[CAR_ID]
      ,'0' as [DELETE_STATUS]
      ,NULL as [PARTY_COUNTRY_ISO_CODE]
      ,NULL as [CAR_COUNTRY_ISO_CODE] 
from MDM_CM..C_REL_PARTY_CAR A
where A.HUB_STATE_IND='1'
and EXISTS (SELECT 1 FROM  MDM_CM..C_B_PARTY B WHERE B.ROWID_OBJECT=A.PARTY_ID AND B.HUB_STATE_IND='1')
and EXISTS (SELECT 1 FROM  MDM_CM..C_B_CAR B WHERE B.ROWID_OBJECT=A.CAR_ID AND B.HUB_STATE_IND='1') ;




	   
	   
	   

	   
	   
	   


	   


	   
	   
